# Generated by Buildr 1.4.0, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "RESTProvider"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Restprovider project"
define "RESTProvider" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "RESTProvider" do
  end

  define "RESTProviderLocalTest" do
    compile.with # Add classpath dependencies
    test.compile.with # Add classpath dependencies
    test.resources
    package(:jar)
  end

  define "RESTProviderTest" do
  end

end
