-- CREATE STATEMENTS
CREATE TABLE IF NOT EXISTS "tableName"("_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "_rid" INTEGER NOT NULL UNIQUE ON CONFLICT REPLACE, "name" TEXT NOT NULL);

-- INSERT DICTS
INSERT INTO dict VALUES (null,"fixture1", "241");

-- INSERT LANDMARKS
INSERT INTO landmarks values(5, "fixture2", 51.5579, -0.102236);
